
#pragma once

#ifndef __TS3DRIVER_GPUAPI_GLCOMMON_OBJECT_ALLOCATOR_H__
#define __TS3DRIVER_GPUAPI_GLCOMMON_OBJECT_ALLOCATOR_H__

#include "../GL_prerequisites.h"

#endif // __TS3DRIVER_GPUAPI_GLCOMMON_OBJECT_ALLOCATOR_H__
