
#ifndef  __TS3_PLATFORM_CONFIG_INTERNAL_ARCH_ARM_H__
#define  __TS3_PLATFORM_CONFIG_INTERNAL_ARCH_ARM_H__

#if !defined( TS3_PCL_MEMORY_BASE_ALIGNMENT )
#  define TS3_PCL_MEMORY_BASE_ALIGNMENT 4
#endif

#endif /*  __TS3_PLATFORM_CONFIG_INTERNAL_ARCH_ARM_H__ */
