
#ifndef  __TS3_PLATFORM_CONFIG_INTERNAL_ARCH_X86_H__
#define  __TS3_PLATFORM_CONFIG_INTERNAL_ARCH_X86_H__

#if !defined( TS3_PCL_MEMORY_BASE_ALIGNMENT )
#  define TS3_PCL_MEMORY_BASE_ALIGNMENT 4
#endif

#define TS3_PCL_ENDIANNESS_NATIVE     TS3_PCL_ENDIANNESS_LE
#define TS3_PCL_ENDIANNESS_NON_NATIVE TS3_PCL_ENDIANNESS_BE
#define TS3_PCL_TARGET_64             0

#endif /*  __TS3_PLATFORM_CONFIG_INTERNAL_ARCH_X86_H__ */
