
#pragma once

#ifndef __TS3DRIVER_GPUAPI_VKCOMMON_CONSTANTS_MAP_H__
#define __TS3DRIVER_GPUAPI_VKCOMMON_CONSTANTS_MAP_H__

namespace ts3::gpuapi
{



}

#endif // __TS3DRIVER_GPUAPI_VKCOMMON_CONSTANTS_MAP_H__
