
#ifndef __TS3_SYSTEM_PLATFORM_OSAPI_ANDROID_COMMON_H__
#define __TS3_SYSTEM_PLATFORM_OSAPI_ANDROID_COMMON_H__

#include <ts3/platform/android/androidNativeAppProxy.h>

namespace ts3
{

    enum : uint32
    {
        SYS_ANDROID_APP_STATE_USER_DATA_INDEX_SYSTEM_CONTEXT,
        SYS_ANDROID_APP_STATE_USER_DATA_INDEX_EVENT_CONTROLLER
    };

}

#endif // __TS3_SYSTEM_PLATFORM_OSAPI_ANDROID_COMMON_H__
