
function( ebsCoreAppend pListName pListSetCache pAppendUniqueOnly pValue )
    if( NOT pValue )
        return()
    endif()
    if( pAppendUniqueOnly )
	    foreach( valueItem ${pValue} )
		    list( APPEND ${pListName} "${valueItem}" )
	    endforeach()
    else()
        set( ${pListName} "${${pListName}};${pValue}" )
    endif()
    if( pListSetCache )
        set( ${pListName} "${${pListName}}" CACHE INTERNAL "${pListName}" )
    else()
        set( ${pListName} "${${pListName}}" PARENT_SCOPE )
    endif()
endfunction()

macro( ebsCoreAppendUniqueInternal pListName pListSetCache pAppendUniqueOnly pContent )
    ebsCoreAppend( ${pListName} "${pListSetCache}" "${pAppendUniqueOnly}" "${pContent}" )
endmacro()

macro( clearInternalCache )
    set( CM_EBS_VARREG "" CACHE INTERNAL "" )
endmacro()

macro( setInternal pVarName )
    set( ${pVarName} "${ARGN}" CACHE INTERNAL "" )
    ebsCoreAppend( CM_EBS_VARREG TRUE TRUE "${pVarName}" )
endmacro()

macro( setLocal pVarName )
    set( ${pVarName} "${ARGN}" )
endmacro()
